baseurl: /
tileUrl: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
defaults:
  -
    scope:
      path: ""
      type: "cities"
    values:
      layout: "city"

collections:
  cities:
    output: true
    permalink: /:path/
